# Generated by Django 5.1.2 on 2024-10-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chatroom_alter_message_room_delete_friendlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
